name: check

on:
  push:
  pull_request:

jobs:
  kernel:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup show
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check kernel
        run: cargo check
      - name: Build kernel
        run: cargo build
